version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: typescript-express-prisma-example-app-1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
